[tox]
envlist =
    py{310, 311, 312, 313}
    codestyle

[testenv]
description = test build
extras =
    test
commands =
    pytest {posargs}

[testenv:codestyle]
changedir = src
description = check code style with flake8
skip_install = true
deps = flake8
commands = flake8 tesstractor --count
